# Generated by Django 5.1.4 on 2025-02-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='receipe_discription',
            new_name='receipe_description',
        ),
    ]
